services:
  - type: web
    name: zenmoney-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: ZENMONEY_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
